"""
Visualization: Lesion vs Random Patch Comparison
================================================

Generates a publication-quality figure showing:
1. Original chest X-ray image
2. Lesion region (ground truth)
3. Random patch generated by rigid translation
4. Statistical comparison

Author: HONER Project
Date: 2026-03-12
"""

import os
import sys
import numpy as np
import torch
import h5py
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from pathlib import Path
import cv2

# Add CheXzero to path
sys.path.insert(0, 'CheXzero')
from multi_metric_attack_framework import (
    generate_equivalent_random_mask,
    extract_lung_region_mask
)
from rsna_attack_framework import RSNADataset


def load_sample_data(dataset, patient_id=None, sample_idx=50):
    """
    Load a sample from the RSNA dataset.

    Args:
        dataset: RSNADataset instance
        patient_id: specific patient ID (optional)
        sample_idx: index to use if patient_id not specified

    Returns:
        image: (3, H, W) tensor, normalized image
        lesion_mask: (H, W) tensor, binary lesion mask
        patient_id: patient ID string
    """
    print("=" * 80)
    print("LOADING SAMPLE DATA")
    print("=" * 80)

    if patient_id is not None:
        # Find patient_id index
        if patient_id not in dataset.patient_ids:
            raise ValueError(f"Patient ID {patient_id} not found!")
        sample_idx = dataset.patient_ids.index(patient_id)

    # Load sample
    sample = dataset[sample_idx]
    image = sample['image']  # (3, 224, 224)
    lesion_mask = sample['mask']  # (3, 224, 224)
    patient_id = sample['patient_id']

    print(f"Patient ID: {patient_id}")
    print(f"Image shape: {image.shape}")
    print(f"Lesion mask shape: {lesion_mask.shape}")

    # Convert lesion mask to 2D (take first channel)
    if lesion_mask.dim() == 3:
        lesion_mask = lesion_mask[0]

    lesion_area = (lesion_mask > 0).sum().item()
    print(f"Lesion area: {lesion_area} pixels")
    print(f"Number of lesions: {sample['num_lesions']}")

    return image, lesion_mask, patient_id


def denormalize_image(image):
    """
    Denormalize CLIP-normalized image to [0, 1] range.

    CLIP normalization:
        mean = [0.48145466, 0.4578275, 0.40821073]
        std = [0.26862954, 0.26130258, 0.27577711]
    """
    mean = torch.tensor([0.48145466, 0.4578275, 0.40821073]).view(3, 1, 1)
    std = torch.tensor([0.26862954, 0.26130258, 0.27577711]).view(3, 1, 1)

    image_denorm = image * std + mean
    image_denorm = torch.clamp(image_denorm, 0, 1)

    return image_denorm


def create_overlay(image, mask, color=(1, 0, 0), alpha=0.4):
    """
    Create colored overlay on image.

    Args:
        image: (3, H, W) tensor in [0, 1]
        mask: (H, W) binary mask
        color: RGB tuple for overlay color
        alpha: transparency (0=transparent, 1=opaque)

    Returns:
        overlay: (3, H, W) tensor with colored overlay
    """
    overlay = image.clone()

    # Convert mask to boolean
    mask_bool = mask > 0

    # Apply color to masked region
    for c in range(3):
        overlay[c][mask_bool] = overlay[c][mask_bool] * (1 - alpha) + color[c] * alpha

    return overlay


def draw_bounding_box(ax, mask, color='red', linewidth=2, linestyle='-', label=None):
    """Draw bounding box around mask region."""
    indices = torch.nonzero(mask, as_tuple=False)

    if len(indices) == 0:
        return

    y_min, x_min = indices.min(dim=0)[0].numpy()
    y_max, x_max = indices.max(dim=0)[0].numpy()

    height = y_max - y_min + 1
    width = x_max - x_min + 1

    rect = mpatches.Rectangle(
        (x_min, y_min), width, height,
        linewidth=linewidth,
        edgecolor=color,
        facecolor='none',
        linestyle=linestyle,
        label=label
    )
    ax.add_patch(rect)

    return (x_min, y_min, width, height)


def create_visualization(image, lesion_mask, random_mask, random_info, patient_id):
    """
    Create comprehensive visualization figure.

    Layout:
        Row 1: Original | Lesion Overlay | Random Patch Overlay
        Row 2: Lesion Only | Random Only | Statistics Table
    """
    print("\n" + "=" * 80)
    print("CREATING VISUALIZATION")
    print("=" * 80)

    # Denormalize image
    image_denorm = denormalize_image(image)
    image_gray = image_denorm.mean(dim=0)  # Grayscale for better contrast

    # Convert to numpy for plotting
    img_np = image_gray.cpu().numpy()
    lesion_np = lesion_mask.cpu().numpy()
    random_np = random_mask[0].cpu().numpy()  # Take first channel

    # Create figure with 2 rows, 3 columns
    fig = plt.figure(figsize=(18, 12))
    gs = fig.add_gridspec(2, 3, hspace=0.3, wspace=0.3)

    # ============================================================
    # Row 1: Original image with overlays
    # ============================================================

    # Panel A: Original image
    ax1 = fig.add_subplot(gs[0, 0])
    ax1.imshow(img_np, cmap='gray')
    ax1.set_title('(A) Original Chest X-ray', fontsize=14, fontweight='bold')
    ax1.axis('off')

    # Panel B: Lesion overlay
    ax2 = fig.add_subplot(gs[0, 1])
    ax2.imshow(img_np, cmap='gray')

    # Overlay lesion in red
    lesion_overlay = np.zeros((*img_np.shape, 3))
    lesion_overlay[lesion_np > 0] = [1, 0, 0]  # Red
    ax2.imshow(lesion_overlay, alpha=0.4)

    # Draw bounding box
    draw_bounding_box(ax2, lesion_mask, color='red', linewidth=2, label='Lesion')

    ax2.set_title('(B) Ground Truth Lesion Region', fontsize=14, fontweight='bold', color='red')
    ax2.axis('off')
    ax2.legend(loc='upper right', fontsize=10)

    # Panel C: Random patch overlay
    ax3 = fig.add_subplot(gs[0, 2])
    ax3.imshow(img_np, cmap='gray')

    # Overlay random patch in blue
    random_overlay = np.zeros((*img_np.shape, 3))
    random_overlay[random_np > 0] = [0, 0.5, 1]  # Blue
    ax3.imshow(random_overlay, alpha=0.4)

    # Draw bounding box
    draw_bounding_box(ax3, random_mask[0], color='blue', linewidth=2, label='Random Patch')

    ax3.set_title('(C) Rigid-Translated Random Patch', fontsize=14, fontweight='bold', color='blue')
    ax3.axis('off')
    ax3.legend(loc='upper right', fontsize=10)

    # ============================================================
    # Row 2: Isolated masks and statistics
    # ============================================================

    # Panel D: Lesion mask only
    ax4 = fig.add_subplot(gs[1, 0])
    ax4.imshow(lesion_np, cmap='Reds', vmin=0, vmax=1)

    # Draw bounding box
    bbox_lesion = draw_bounding_box(ax4, lesion_mask, color='darkred', linewidth=2)

    ax4.set_title('(D) Lesion Mask', fontsize=14, fontweight='bold')
    ax4.axis('off')

    # Add bbox dimensions
    if bbox_lesion:
        x, y, w, h = bbox_lesion
        ax4.text(5, 20, f'Bbox: {h}x{w}', color='white', fontsize=10,
                bbox=dict(boxstyle='round', facecolor='red', alpha=0.7))

    # Panel E: Random patch mask only
    ax5 = fig.add_subplot(gs[1, 1])
    ax5.imshow(random_np, cmap='Blues', vmin=0, vmax=1)

    # Draw bounding box
    bbox_random = draw_bounding_box(ax5, random_mask[0], color='darkblue', linewidth=2)

    ax5.set_title('(E) Random Patch Mask', fontsize=14, fontweight='bold')
    ax5.axis('off')

    # Add bbox dimensions
    if bbox_random:
        x, y, w, h = bbox_random
        ax5.text(5, 20, f'Bbox: {h}x{w}', color='white', fontsize=10,
                bbox=dict(boxstyle='round', facecolor='blue', alpha=0.7))

    # Panel F: Statistics table
    ax6 = fig.add_subplot(gs[1, 2])
    ax6.axis('off')

    # Compute statistics
    lesion_area = (lesion_np > 0).sum()
    random_area = (random_np > 0).sum()
    area_error = abs(random_area - lesion_area)
    area_error_pct = (area_error / lesion_area * 100) if lesion_area > 0 else 0

    # Get bounding box sizes
    lesion_indices = np.argwhere(lesion_np > 0)
    if len(lesion_indices) > 0:
        lesion_bbox_h = lesion_indices[:, 0].max() - lesion_indices[:, 0].min() + 1
        lesion_bbox_w = lesion_indices[:, 1].max() - lesion_indices[:, 1].min() + 1
    else:
        lesion_bbox_h, lesion_bbox_w = 0, 0

    random_indices = np.argwhere(random_np > 0)
    if len(random_indices) > 0:
        random_bbox_h = random_indices[:, 0].max() - random_indices[:, 0].min() + 1
        random_bbox_w = random_indices[:, 1].max() - random_indices[:, 1].min() + 1
    else:
        random_bbox_h, random_bbox_w = 0, 0

    # Create statistics text
    stats_text = f"""
    RIGID TRANSLATION COMPARISON
    {"=" * 45}

    Patient ID: {patient_id[:20]}...

    LESION REGION (Ground Truth):
      - Pixel Count (L0):    {lesion_area:,} pixels
      - Bounding Box:         {lesion_bbox_h} x {lesion_bbox_w}
      - Bbox Area:            {lesion_bbox_h * lesion_bbox_w:,} pixels
      - Fill Ratio:           {lesion_area / (lesion_bbox_h * lesion_bbox_w) * 100:.1f}%

    RANDOM PATCH (Rigid Translation):
      - Pixel Count (L0):    {random_area:,} pixels
      - Bounding Box:         {random_bbox_h} x {random_bbox_w}
      - Bbox Area:            {random_bbox_h * random_bbox_w:,} pixels
      - Fill Ratio:           {random_area / (random_bbox_h * random_bbox_w) * 100:.1f}%
      - Translation:          ({random_info['x']}, {random_info['y']})
      - Attempts:             {random_info['attempts']}

    L0 ALIGNMENT VALIDATION:
      - Area Difference:      {area_error} pixels
      - Relative Error:       {area_error_pct:.4f}%
      - Match Status:         {"EXACT" if area_error == 0 else "MISMATCH"}
      - Method:               {random_info['method']}

    TISSUE VALIDATION:
      - Mean Intensity:       {random_info['mean_intensity']:.3f}
      - Tissue Valid:         {random_info['tissue_valid']}
      - Overlap Ratio:        {random_info['overlap_ratio']:.1%}
      - In Lung Ratio:        {random_info['in_lung_ratio']:.1%}

    {"=" * 45}
    KEY INSIGHT: The random patch preserves the
    EXACT spatial structure of the lesion, only
    translating it to a different location. This
    eliminates "shape concentration" as a
    confounding variable.
    """

    ax6.text(0.05, 0.95, stats_text, transform=ax6.transAxes,
            fontsize=9, verticalalignment='top', fontfamily='monospace',
            bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8))

    ax6.set_title('(F) Statistical Comparison', fontsize=14, fontweight='bold')

    # Overall title
    fig.suptitle('Rigid Translation Method: Lesion vs Random Patch Comparison',
                fontsize=16, fontweight='bold', y=0.98)

    return fig


def main():
    """Main execution"""
    print("\n" + "=" * 80)
    print("LESION VS RANDOM PATCH VISUALIZATION")
    print("=" * 80)

    # Output directory
    output_dir = Path('results/weekly_report')
    output_dir.mkdir(exist_ok=True, parents=True)

    # Load dataset
    print("\nLoading RSNA dataset...")
    dataset = RSNADataset(
        h5_path='dataset/rsna/rsna_200_samples.h5',
        lesion_info_path='dataset/rsna/rsna_200_lesion_info.json'
    )
    print(f"Dataset loaded: {len(dataset)} samples")

    # Load a sample (you can change sample_idx or specify patient_id)
    # Try to load a sample with moderate lesion size for good visualization
    image, lesion_mask, patient_id = load_sample_data(dataset, sample_idx=50)

    # Expand lesion mask to 3 channels
    lesion_mask_3ch = lesion_mask.unsqueeze(0).expand(3, -1, -1)

    # Extract lung mask
    print("\nExtracting lung region mask...")
    lung_mask = extract_lung_region_mask(image, threshold_method='otsu')

    # Generate random patch using rigid translation
    print("\nGenerating random patch via rigid translation...")
    try:
        random_mask, random_info = generate_equivalent_random_mask(
            lesion_mask=lesion_mask_3ch,
            lung_mask=lung_mask,
            image=image,
            max_attempts=1000,
            overlap_threshold=0.1,
            tissue_intensity_threshold=-1.0
        )

        print(f"\n[SUCCESS] Random patch generated!")
        print(f"  Method: {random_info['method']}")
        print(f"  Area match: {random_info['area_match']}")
        print(f"  Area error: {random_info['area_error_ratio']:.4%}")
        print(f"  Attempts: {random_info['attempts']}")

    except Exception as e:
        print(f"\n[ERROR] Failed to generate random patch: {e}")
        print("This patient may have a lesion too large for placement.")
        return 1

    # Create visualization
    fig = create_visualization(image, lesion_mask, random_mask, random_info, patient_id)

    # Save figure
    output_path = output_dir / f'methodology_visualization_{patient_id[:8]}.png'
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    print(f"\n[OK] Saved: {output_path}")

    # Also create a simplified version for presentations
    output_path_simple = output_dir / f'methodology_simple_{patient_id[:8]}.png'

    fig_simple, axes = plt.subplots(1, 3, figsize=(15, 5))

    image_denorm = denormalize_image(image)
    img_np = image_denorm.mean(dim=0).cpu().numpy()
    lesion_np = lesion_mask.cpu().numpy()
    random_np = random_mask[0].cpu().numpy()

    # Original
    axes[0].imshow(img_np, cmap='gray')
    axes[0].set_title('Original Image', fontsize=14, fontweight='bold')
    axes[0].axis('off')

    # Lesion
    axes[1].imshow(img_np, cmap='gray')
    lesion_overlay = np.zeros((*img_np.shape, 3))
    lesion_overlay[lesion_np > 0] = [1, 0, 0]
    axes[1].imshow(lesion_overlay, alpha=0.5)
    axes[1].set_title(f'Lesion Region\n({(lesion_np > 0).sum():,} pixels)',
                     fontsize=14, fontweight='bold', color='red')
    axes[1].axis('off')

    # Random
    axes[2].imshow(img_np, cmap='gray')
    random_overlay = np.zeros((*img_np.shape, 3))
    random_overlay[random_np > 0] = [0, 0.5, 1]
    axes[2].imshow(random_overlay, alpha=0.5)
    axes[2].set_title(f'Random Patch\n({(random_np > 0).sum():,} pixels)',
                     fontsize=14, fontweight='bold', color='blue')
    axes[2].axis('off')

    plt.suptitle('Spatial Attack Mode Comparison', fontsize=16, fontweight='bold')
    plt.tight_layout()
    plt.savefig(output_path_simple, dpi=300, bbox_inches='tight')
    print(f"[OK] Saved: {output_path_simple}")

    plt.close('all')

    print("\n" + "=" * 80)
    print("[COMPLETE] Visualization generated successfully!")
    print("=" * 80)
    print(f"\nOutput files:")
    print(f"  1. Detailed: {output_path}")
    print(f"  2. Simple:   {output_path_simple}")
    print("\n" + "=" * 80)

    # Cleanup
    dataset.close()

    return 0


if __name__ == "__main__":
    exit(main())
