"""
unified_attacks.py

A small "unified API" layer that lets you call multiple adversarial attacks
through a consistent interface, while still reusing your existing codebases.

- PGD: TF1 graph-gradient (expects a TF1-style model with x_input/y_input/logits)
- C&W: wraps the Carlini-Wagner implementations (L2 / L∞ / L0) from Carlini (2016/2017)

Designed so you can later add FGSM / DeepFool with minimal changes.

Author: (generated by ChatGPT)
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Literal, Optional, Union

import numpy as np

try:
    import tensorflow as tf  # TF1.x / TF2 in compat.v1
except Exception as e:  # pragma: no cover
    tf = None  # type: ignore


Norm = Literal["linf", "l2", "l0"]


# -----------------------------
# Common config + small helpers
# -----------------------------

@dataclass
class AttackConfig:
    """Common attack configuration.

    Notes
    -----
    - clip_min/clip_max are the *valid input range* in the same scale as x.
      For CIFAR in your PGD code you use [0, 255]. In many ML repos it's [0, 1]
      or [-0.5, 0.5]. Keep it consistent with the model's expected preprocessing.
    """
    norm: Norm = "linf"

    # Constraint / step params
    epsilon: float = 8.0
    num_steps: int = 10
    step_size: float = 2.0
    random_start: bool = True

    # Input range clamp (after every step)
    clip_min: float = 0.0
    clip_max: float = 255.0

    # Loss / objective options
    loss: Literal["xent", "cw_margin"] = "xent"
    cw_kappa: float = 50.0  # margin used in your PGD "cw" style loss


def _ensure_numpy(x: Any) -> np.ndarray:
    if isinstance(x, np.ndarray):
        return x
    return np.asarray(x)


def _is_onehot(y: np.ndarray) -> bool:
    return y.ndim == 2 and np.all((y == 0) | (y == 1)) and np.allclose(y.sum(axis=1), 1.0)


def to_onehot(y: Union[np.ndarray, list], num_classes: int) -> np.ndarray:
    y = _ensure_numpy(y)
    if _is_onehot(y):
        return y.astype(np.float32)
    if y.ndim != 1:
        raise ValueError(f"Expected label vector shape (N,), got {y.shape}")
    oh = np.zeros((y.shape[0], num_classes), dtype=np.float32)
    oh[np.arange(y.shape[0]), y.astype(int)] = 1.0
    return oh


# -----------------------------
# Base interface
# -----------------------------

class AttackBase:
    """All attacks expose the same method: generate(x, y, sess=...)."""

    def generate(self, x: np.ndarray, y: np.ndarray, sess: Optional[Any] = None) -> np.ndarray:
        raise NotImplementedError


# ==========================================================
# 1) PGD (TF1) — supports Linf now; can extend to L2 later
# ==========================================================

class PGDLinfTF1Attack(AttackBase):
    """PGD under L∞ constraint (TF1 graph gradients).

    Expected model interface (TF1-style):
      - model.x_input: tf.placeholder/tensor, shape [None, H, W, C]
      - model.y_input: tf.placeholder/tensor, shape [None] (int labels) or [None, K] (one-hot)
      - model.pre_softmax: logits tensor for model.x_input, shape [None, K]
      - model.xent: cross-entropy loss tensor (can be sum over batch)

    This mirrors the LinfPGDAttack class you pasted, but exposes a unified generate() API.
    """

    def __init__(self, model: Any, config: AttackConfig, num_classes: int = 10):
        if tf is None:
            raise RuntimeError("TensorFlow is not available in this environment.")
        self.model = model
        self.cfg = config
        self.num_classes = num_classes

        # Build loss op (graph)
        self._loss = self._build_loss_op()
        self._grad = tf.gradients(self._loss, self.model.x_input)[0]

    def _build_loss_op(self):
        # Default: use model.xent if present (matches your snippet)
        if self.cfg.loss == "xent":
            if hasattr(self.model, "xent"):
                return self.model.xent
            # fallback: build xent from logits
            logits = getattr(self.model, "pre_softmax")
            y_in = self.model.y_input
            if y_in.dtype.is_integer:
                y_oh = tf.one_hot(y_in, self.num_classes, dtype=tf.float32)
            else:
                y_oh = tf.cast(y_in, tf.float32)
            return tf.reduce_sum(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y_oh))

        # CW-style margin loss used in your PGD code ("cw")
        logits = getattr(self.model, "pre_softmax")
        y_in = self.model.y_input

        if y_in.dtype.is_integer:
            y_oh = tf.one_hot(y_in, self.num_classes, dtype=tf.float32)
        else:
            y_oh = tf.cast(y_in, tf.float32)

        correct_logit = tf.reduce_sum(y_oh * logits, axis=1)
        wrong_logit = tf.reduce_max((1 - y_oh) * logits - 1e4 * y_oh, axis=1)
        # identical structure to your code; kappa controlled by cfg.cw_kappa
        loss_vec = -tf.nn.relu(correct_logit - wrong_logit + self.cfg.cw_kappa)
        return tf.reduce_sum(loss_vec)

    def generate(self, x: np.ndarray, y: np.ndarray, sess: Optional[Any] = None) -> np.ndarray:
        if sess is None:
            raise ValueError("PGDLinfTF1Attack requires an active tf.Session passed as sess=...")

        x_nat = _ensure_numpy(x).astype(np.float32)
        y_in = _ensure_numpy(y)

        # Random start in the epsilon-ball
        if self.cfg.random_start:
            x_adv = x_nat + np.random.uniform(-self.cfg.epsilon, self.cfg.epsilon, x_nat.shape).astype(np.float32)
            x_adv = np.clip(x_adv, self.cfg.clip_min, self.cfg.clip_max)
        else:
            x_adv = x_nat.copy()

        # Iterative updates
        for _ in range(int(self.cfg.num_steps)):
            grad = sess.run(
                self._grad,
                feed_dict={self.model.x_input: x_adv, self.model.y_input: y_in},
            )
            x_adv = x_adv + self.cfg.step_size * np.sign(grad).astype(np.float32)

            # Project back to Linf ball
            x_adv = np.clip(x_adv, x_nat - self.cfg.epsilon, x_nat + self.cfg.epsilon)
            # Clamp to valid input range
            x_adv = np.clip(x_adv, self.cfg.clip_min, self.cfg.clip_max)

        return x_adv


# ==========================================================
# 2) Carlini & Wagner — wraps the provided implementations
# ==========================================================

class CWAttack(AttackBase):
    """Wrapper for the Carlini-Wagner attacks from Carlini (L2/L∞/L0).

    Expected model interface (Carlini repo style):
      - model.predict(x_tensor): returns logits (pre-softmax) for x_tensor
      - model.image_size, model.num_channels, model.num_labels

    Targets:
      - For targeted CW: pass y as one-hot targets (N, K)
      - For untargeted CW: pass y as one-hot *true labels* and set targeted=False when creating the attacker
    """

    def __init__(
        self,
        sess: Any,
        model: Any,
        norm: Norm = "l2",
        targeted: bool = True,
        cw_kwargs: Optional[Dict[str, Any]] = None,
    ):
        if tf is None:
            raise RuntimeError("TensorFlow is not available in this environment.")
        self.sess = sess
        self.model = model
        self.norm = norm
        self.targeted = targeted
        self.cw_kwargs = cw_kwargs or {}

        # Import lazily so this file can be used without the CW files if needed
        if norm == "l2":
            from l2_attack import CarliniL2  # noqa: F401
            self._attacker = CarliniL2(sess, model, targeted=targeted, **self.cw_kwargs)
        elif norm == "linf":
            from li_attack import CarliniLi  # noqa: F401
            self._attacker = CarliniLi(sess, model, targeted=targeted, **self.cw_kwargs)
        elif norm == "l0":
            from l0_attack import CarliniL0  # noqa: F401
            self._attacker = CarliniL0(sess, model, targeted=targeted, **self.cw_kwargs)
        else:
            raise ValueError(f"Unsupported norm for CWAttack: {norm}")

    def generate(self, x: np.ndarray, y: np.ndarray, sess: Optional[Any] = None) -> np.ndarray:
        # sess kept for unified signature; CW attacker already owns the session
        x = _ensure_numpy(x).astype(np.float32)
        y = _ensure_numpy(y).astype(np.float32)
        return self._attacker.attack(x, y)


# ==========================================================
# 3) Factory (optional convenience)
# ==========================================================

def make_attack(
    name: Literal["pgd", "cw"],
    *,
    model: Any,
    sess: Optional[Any] = None,
    config: Optional[AttackConfig] = None,
    cw_norm: Norm = "l2",
    cw_targeted: bool = True,
    cw_kwargs: Optional[Dict[str, Any]] = None,
) -> AttackBase:
    """Create an attack with a consistent call signature."""
    if name == "pgd":
        if config is None:
            config = AttackConfig(norm="linf")
        if config.norm != "linf":
            raise ValueError("This PGD wrapper currently implements only Linf. Extend if needed.")
        return PGDLinfTF1Attack(model=model, config=config)
    elif name == "cw":
        if sess is None:
            raise ValueError("CWAttack requires a tf.Session passed as sess=...")
        return CWAttack(sess=sess, model=model, norm=cw_norm, targeted=cw_targeted, cw_kwargs=cw_kwargs)
    else:
        raise ValueError(f"Unknown attack name: {name}")


# ==========================================================
# 4) Stubs for later (FGSM / DeepFool)
# ==========================================================

class FGSMLinfTF1Attack(PGDLinfTF1Attack):
    """FGSM is PGD with num_steps=1. Keep it as a thin subclass."""
    def __init__(self, model: Any, epsilon: float, loss: Literal["xent", "cw_margin"] = "xent",
                 clip_min: float = 0.0, clip_max: float = 255.0, num_classes: int = 10):
        cfg = AttackConfig(norm="linf", epsilon=epsilon, num_steps=1, step_size=epsilon,
                           random_start=False, clip_min=clip_min, clip_max=clip_max, loss=loss)
        super().__init__(model=model, config=cfg, num_classes=num_classes)


class DeepFoolAttackPlaceholder(AttackBase):
    """Placeholder: DeepFool typically optimizes for *minimal L2* perturbation.
    You can later implement or wrap an existing implementation here.
    """
    def generate(self, x: np.ndarray, y: np.ndarray, sess: Optional[Any] = None) -> np.ndarray:  # pragma: no cover
        raise NotImplementedError("DeepFool not implemented yet in this unified layer.")
